In [398]:
import pandas as pd
import numpy as np 
from pandas import Series,DataFrame
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style('whitegrid')
from datetime import datetime
import os
import random 
import seaborn as sns
import functools
from fbprophet import Prophet
from statistics import mean
from sklearn.metrics import r2_score

In [388]:
data = pd.read_csv(os.path.expanduser("~/Desktop/DS_Competition/ucsbdata.csv")).dropna(axis=0)
data['Index']=pd.to_datetime(data['Index'])
data = data.drop(['OPEN', 'HIGH', 'LOW'], axis=1) 

data_2018 = data[499:-251] #1/02/2009 - 12/29/2017    
data = data[499:] #1/02/2009 - 12/31/2018 
data.tail()

,Index,R,US10YR,EPS,PER,CLOSE,BDIY,VIX,PCR,MVOLE,...,MYSTERYVAR3,TOM,HULBERTSENTIMENT,BUBBLE,CASH,DEBT,DIVIDEND,RETURN,STOCKS,WAR
16858,2018-12-24,0.022629,2.7383,132.51,17.696918,2351.10,1271.0,36.07,0.79,11037.81,...,12.133489,0,-11.74,61.833407,145.063192,41.207903,76.017489,32.030824,51.823052,31.871601
16859,2018-12-26,0.007556,2.8079,132.50,18.622795,2467.70,1271.0,30.41,0.62,19311.44,...,12.338862,1,-14.94,55.718015,120.402449,29.434217,55.868275,28.959375,44.785354,32.472952
16860,2018-12-27,-0.001382,2.7666,132.51,18.778925,2488.83,1271.0,29.96,0.73,17158.61,...,12.115016,1,-15.59,67.948799,121.853081,36.498429,57.700022,39.051278,47.344517,37.283760
16861,2018-12-28,0.008630,2.7182,132.51,18.758886,2485.74,1271.0,28.34,0.44,15667.72,...,12.042282,1,-15.59,61.833407,124.754345,41.796588,73.269869,39.490056,51.823052,36.682409
16862,2018-12-31,0.000947,2.6842,132.52,18.919920,2506.85,1271.0,25.42,0.60,15284.06,...,12.067827,1,-11.74,61.153919,137.810032,42.973956,79.680982,36.857386,47.344517,36.682409

In [389]:
df_prophet=data_2018[['Index','R']]
df_prophet=df_prophet.sort_values('Index')
df_prophet=df_prophet.rename(columns={'Index':'ds','R':'y'})

df_prophet.tail(3)

              ds         y
16609 2017-12-27  0.002001
16610 2017-12-28 -0.003831
16611 2017-12-29  0.007078

In [390]:
m=Prophet()
m.fit(df_prophet)


future=m.make_future_dataframe(periods=365)

future.tail()
forecast=m.predict(future)
forecast.head(5)

INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2009-01-02,0.000392,-0.010930,0.011674,0.000392,0.000392,-0.000176,-0.000176,-0.000176,0.000234,0.000234,0.000234,-0.000410,-0.000410,-0.000410,0.0,0.0,0.0,0.000216
1,2009-01-05,0.000391,-0.011053,0.011664,0.000391,0.000391,-0.000656,-0.000656,-0.000656,0.000353,0.000353,0.000353,-0.001009,-0.001009,-0.001009,0.0,0.0,0.0,-0.000265
2,2009-01-06,0.000391,-0.011456,0.011175,0.000391,0.000391,-0.000732,-0.000732,-0.000732,0.000473,0.000473,0.000473,-0.001204,-0.001204,-0.001204,0.0,0.0,0.0,-0.000340
3,2009-01-07,0.000391,-0.012860,0.010362,0.000391,0.000391,-0.000893,-0.000893,-0.000893,0.000498,0.000498,0.000498,-0.001391,-0.001391,-0.001391,0.0,0.0,0.0,-0.000502
4,2009-01-08,0.000391,-0.012165,0.010040,0.000391,0.000391,-0.001542,-0.001542,-0.001542,0.000021,0.000021,0.000021,-0.001563,-0.001563,-0.001563,0.0,0.0,0.0,-0.001151

In [391]:
results = forecast.drop(['trend', 'yhat_lower', 'yhat_upper','trend_lower', 'trend_upper', 'additive_terms', 'additive_terms_lower',
                        'additive_terms_upper', 'weekly','weekly_lower','weekly_upper','yearly','yearly_lower','yearly_upper',
                        'multiplicative_terms','multiplicative_terms_lower','multiplicative_terms_upper'], axis=1) 
results = results[:-1]


results.rename(columns = {'yhat':'PREDICTED'}, inplace = True) 
results.set_index('ds')

            PREDICTED
ds
2009-01-02   0.000216
2009-01-05  -0.000265
2009-01-06  -0.000340
2009-01-07  -0.000502
2009-01-08  -0.001151
2009-01-09  -0.001093
2009-01-12  -0.001299
2009-01-13  -0.001230
2009-01-14  -0.001226
2009-01-15  -0.001690
2009-01-16  -0.001432
2009-01-20  -0.000706
2009-01-21  -0.000494
2009-01-22  -0.000764
2009-01-23  -0.000329
2009-01-26   0.000499
2009-01-27   0.000853
2009-01-28   0.001103
2009-01-29   0.000838
2009-01-30   0.001244
2009-02-02   0.001799
2009-02-03   0.002008
2009-02-04   0.002090
2009-02-05   0.001640
2009-02-06   0.001847
2009-02-09   0.001778
2009-02-10   0.001787
2009-02-11   0.001681
2009-02-12   0.001059
2009-02-13   0.001116
...               ...
2018-11-29   0.000438
2018-11-30   0.000611
2018-12-01  -0.000451
2018-12-02  -0.000489
2018-12-03   0.000619
2018-12-04   0.000711
2018-12-05   0.000715
2018-12-06   0.000226
2018-12-07   0.000436
2018-12-08  -0.000579
2018-12-09  -0.000559
2018-12-10   0.000613
2018-12-11   0.000773
2018-12-12   0.000848
2018-12-13   0.000429
2018-12-14   0.000706
2018-12-15  -0.000249
2018-12-16  -0.000179
2018-12-17   0.001032
2018-12-18   0.001217
2018-12-19   0.001301
2018-12-20   0.000874
2018-12-21   0.001124
2018-12-22   0.000124
2018-12-23   0.000129
2018-12-24   0.001258
2018-12-25   0.001344
2018-12-26   0.001314
2018-12-27   0.000761
2018-12-28   0.000875

[2629 rows x 1 columns]

# Check that Predicted R-Average for 2018 is similar to actual R-average (0.0008706)

In [399]:
R_values = data[:-1]
R_values.drop(['US10YR','ASP', 'TERM', 'VRP', 
         'LOAN','DXY', 'HTIME', 'LTIME', 'IC', 
         'INF', 'UR', 'URR', 'HS', 'FOMC', 'PPIR', 
         'NAPMPMI', 'NAPMNEWO', 'NAPMPRIC', 'PTB', 'CATY','PCR', 'NOS', 'MVOLE', 'NYSEADV', 'RV',
         'RELINF', 'SIM', 'TOM', 'BDIY', 'SENTIMENT1',
         'SENTIMENT2', 'SENTIMENT3', 'SENTIMENT4', 'HULBERTSENTIMENT',
         'MYSTERYVAR1', 'MYSTERYVAR2','DEBT', 'RETURN', 'STOCKS', 'WAR','EPS','PER','CLOSE','VIX','ADVDECL', 'BAA',
              'BER', 'DEL', 'BBY', 'TYVIX', 'CRP', 'INDPRO', 'CAPE', 'FEDFUNDS', 'DVY', 'AAA', 'SI',
              'VVIX', 'US3M', 'MYSTERYVAR3', 'CASH', 'DIVIDEND', 'BUBBLE'], axis=1)
R_values=R_values[['Index','R']].sort_values('Index')
R_values=R_values.rename(columns={'Index':'ds','R':'y'})
R_values.set_index('ds')
Copy_Target = R_values


result = results.merge(R_values, on='ds', how='inner') 
result.rename(columns={'ds':'date','PREDICTED':'prediction', 'y':'target'}, inplace=True)
result.head(10)

        date  prediction    target
0 2009-01-02    0.000216 -0.001187
1 2009-01-05   -0.000265  0.006650
2 2009-01-06   -0.000340 -0.022717
3 2009-01-07   -0.000502  0.004069
4 2009-01-08   -0.001151 -0.021655
5 2009-01-09   -0.001093 -0.022731
6 2009-01-12   -0.001299  0.001834
7 2009-01-13   -0.001230 -0.022745
8 2009-01-14   -0.001226  0.000352
9 2009-01-15   -0.001690  0.007785

In [401]:
prediction_avg = mean(result['prediction'])
target_avg = mean(result['target'])

percent_err = (abs(target_avg - prediction_avg)/(target_avg)) * 100

print("Average Predicted R value for 2018:", prediction_avg) 
print("Average Actual R Value for 2018:", target_avg)
print("Average Error:", percent_err, "\n")
R2 = r2_score(result['target'], result['prediction'])
score = 0.00087

print("Benchmark R^2 ----->", score)
print("Our R^2 Score ----->", round(R2,5))

Average Predicted R value for 2018: 0.000598748534729625
Average Actual R Value for 2018: 0.000534048394494265
Average Error: 12.115033188449141

Benchmark R^2 -----> 0.00087
Our R^2 Score -----> 0.00604

# Prophet Model for test 2: Concat 2019 data: [date, target(R Values)] to our 2009-2018 Train Set

In [409]:
prophet_2019 =  data[['Index','R']]
prophet_2019=prophet_2019.sort_values('Index')
prophet_2019=prophet_2019.rename(columns={'Index':'ds','R':'y'})

prophet_2019.tail(3)

              ds         y
16860 2018-12-27 -0.001382
16861 2018-12-28  0.008630
16862 2018-12-31  0.000947

Hold = 1,734
Prophet = 1,858
Prophet Thresh = 1,399
Seasonality = 1,953
Optimized Prophet Thresh = 1,663

In [410]:
m=Prophet()
m.fit(prophet_2019)


future=m.make_future_dataframe(periods=365)

future.tail()
forecast=m.predict(future)
forecast.tail(5)

INFO:fbprophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
2876,2019-12-27,-0.00001,-0.010893,0.011505,-0.000010,-0.00001,0.000468,0.000468,0.000468,0.000189,0.000189,0.000189,0.000279,0.000279,0.000279,0.0,0.0,0.0,0.000458
2877,2019-12-28,-0.00001,-0.011738,0.011507,-0.000010,-0.00001,-0.000497,-0.000497,-0.000497,-0.000792,-0.000792,-0.000792,0.000295,0.000295,0.000295,0.0,0.0,0.0,-0.000507
2878,2019-12-29,-0.00001,-0.011200,0.011349,-0.000010,-0.00001,-0.000498,-0.000498,-0.000498,-0.000792,-0.000792,-0.000792,0.000294,0.000294,0.000294,0.0,0.0,0.0,-0.000508
2879,2019-12-30,-0.00001,-0.010107,0.012143,-0.000011,-0.00001,0.000758,0.000758,0.000758,0.000484,0.000484,0.000484,0.000274,0.000274,0.000274,0.0,0.0,0.0,0.000748
2880,2019-12-31,-0.00001,-0.010774,0.011752,-0.000011,-0.00001,0.000741,0.000741,0.000741,0.000505,0.000505,0.000505,0.000236,0.000236,0.000236,0.0,0.0,0.0,0.000731

In [411]:
results = forecast.drop(['trend', 'yhat_lower', 'yhat_upper','trend_lower', 'trend_upper', 'additive_terms', 'additive_terms_lower',
                        'additive_terms_upper', 'weekly','weekly_lower','weekly_upper','yearly','yearly_lower','yearly_upper',
                        'multiplicative_terms','multiplicative_terms_lower','multiplicative_terms_upper'], axis=1) 
results = results[:-3]



results.rename(columns = {'yhat':'PREDICTED'}, inplace = True) 
results.set_index('ds')

target_same = Copy_Target[1762:]
target_same['ds'] = target_same['ds'].astype('datetime64') + pd.offsets.DateOffset(years=1)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':

In [412]:
results = results.merge(target_same, on='ds', how='inner') 
results.rename(columns={'ds':'date','PREDICTED':'prediction', 'y':'target'}, inplace=True)

In [413]:
results.tail(20)

          date  prediction    target
618 2019-11-29    0.000399  0.005986
619 2019-11-30   -0.000648  0.013065
620 2019-12-03    0.000415 -0.022066
621 2019-12-04    0.000308 -0.001611
622 2019-12-06   -0.000134 -0.022072
623 2019-12-07   -0.001181  0.001804
624 2019-12-10   -0.000024  0.000134
625 2019-12-11   -0.000070  0.004930
626 2019-12-12   -0.000629 -0.000432
627 2019-12-13   -0.000359 -0.018730
628 2019-12-14   -0.001318 -0.019905
629 2019-12-17    0.000120 -0.001188
630 2019-12-18    0.000161 -0.015181
631 2019-12-19   -0.000317 -0.016503
632 2019-12-20    0.000023 -0.020671
633 2019-12-21   -0.000878 -0.022094
634 2019-12-24    0.000638  0.022629
635 2019-12-26    0.000164  0.007556
636 2019-12-27    0.000458 -0.001382
637 2019-12-28   -0.000507  0.008630

In [414]:
R2 = r2_score(results['target'], results['prediction'])
score = -0.0162

print("Benchmark R^2 ----->", score)
print("Our R^2 Score ----->", round(R2,5))

Benchmark R^2 -----> -0.0162
Our R^2 Score -----> 0.00181